media: docs/media
content:
  - name: docs
    label: Docs
    path: docs
    type: collection
    fields:
      - { name: title, lable: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, lable: Date, type: date }
      - { name: description, lable: Description, type: string, options: { maxlength: 160 } }
      - { name: image, lable: Image, type: image }
      - { name: body, lable: Body, type: rich-text }